// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RPInfo = { id: string, name: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserInfo = { id: string, name: string, displayName: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PubKeyCredParam = { type: "public-key", alg: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthenticatorSelection = { residentKey: ResidentKeyRequirement, requireResidentKey: boolean, userVerification: UserVerificationRequirement, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicKeyCredentialCreationOptions = { rp: RPInfo, user: UserInfo, challenge: string, pubKeyCredParams: Array<PubKeyCredParam>, timeout: number, authenticatorSelection: AuthenticatorSelection, attestation: AttestationConveyancePreference, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AllowCredential = { type: "public-key", id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicKeyCredentialRequestOptions = { challenge: string, timeout: number, rpId: string, allowCredentials: Array<AllowCredential>, userVerification: UserVerificationRequirement, };